version: '3'
networks:
  local-service:
    driver: bridge
services:
  mysql:
    image: mariadb
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: TheMatrixHasYou!
      MYSQL_USER: neo
      MYSQL_PASSWORD: white_rabbit
    command: --sql_mode=""
    networks:
      - local-service
    volumes:
      - ./scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql